[toolchain]

[features]
seeds = true
skip-lint = false

[programs.localnet]
anchor_movie_review_program = "62hFzjxKcWwR3i1F76czzxsQP5UHSGE5HbKNhcSwbPSu"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/flynn/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
